language: python

matrix:
  include:
    - python: 2.7
      env: TOX_ENV=pyflakes
    - python: pypy
      env: TOX_ENV=pypy
    - python: 2.7
      env: TOX_ENV=test-py27-codecov-travis

install:
    - pip install tox

script: tox -e $TOX_ENV

notifications:
    email: false
