language: python

matrix:
  include:
    - python: 3.6
      env: TOX_ENV=pyflakes
    - python: 3.6
      env: TOX_ENV=test-py36
    - python: 3.7
      env: TOX_ENV=test-py37
    - python: 3.8
      env: TOX_ENV=test-py38-codecov-travis
    - python: 3.8
      env: TOX_ENV=twisted-apidoc
    - python: pypy3
      env: TOX_ENV=test-pypy3

  allow_failures:
    # Twisted trunk is broken for now.
    - env: TOX_ENV=twisted-apidoc

install:
    - pip install tox

script: tox -e $TOX_ENV

notifications:
    email: false

# Do an automatic PyPi release when a tag is created.
# http://docs.travis-ci.com/user/deployment/pypi/
# Make sure builds are triggered for any push so that the tag push will also
# trigger a build.
deploy:
  provider: pypi
  # twistedchecker-robot is associated with adi.roiban email address from
  # Gmail. It uses a random password which was not recorded in plain text.
  username: "__token__"
  on:
    tags: true
    # All branches is still required.
    # https://github.com/travis-ci/travis-ci/issues/1675
    all_branches: true
    condition: "$TOX_ENV = test-py38-codecov-travis"
