name: Generate and publish pydoctor docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Pydoctor
      run: |
        python -m pip install .

    - name: Log system information
      run: |
        test -r /etc/os-release && sh -c '. /etc/os-release && echo "OS: $PRETTY_NAME"'
        python --version
        python -c "print('\nENVIRONMENT VARIABLES\n=====================\n')"
        python -c "import os; [print(f'{k}={v}') for k, v in os.environ.items()]"

    - name: Build documentation
      run: |
        # Allow pydoctor to exit with non-zero status code
        set +e

        # Run pydoctor build
        pydoctor \
            --add-package=pydoctor \
            --project-name=pydoctor \
            --project-url=https://github.com/$GITHUB_REPOSITORY \
            --html-viewsource-base https://github.com/$GITHUB_REPOSITORY/tree/$GITHUB_SHA \
            --make-html \
            --html-output=./apidocs \
            --project-base-dir "$(pwd)" \
            --docformat=restructuredtext

    - name: Publish Pydoctor documentation to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./apidocs
        commit_message: "Generate Pydoctor documentation"
        destination_dir: apidocs
        keep_files: true