name: Generate and publish sphinx docs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  static_checks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Sphinx
      run: |
        python -m pip install -U Sphinx

    - name: Install Pydoctor
      run: |
        python -m pip install .

    - name: Log system information
      run: |
        test -r /etc/os-release && sh -c '. /etc/os-release && echo "OS: $PRETTY_NAME"'
        python --version
        python -c "print('\nENVIRONMENT VARIABLES\n=====================\n')"
        python -c "import os; [print(f'{k}={v}') for k, v in os.environ.items()]"

    - name: Build documentation
      run: |
        # Dynamically generate full help
        pydoctor --help > ./docs/source/help.txt
        
        # Build
        cd docs
        make html

    - name: Publish Sphinx documentation to the gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/build/html
        commit_message: "Generate Sphinx documentation"
        keep_files: true
